name: CI PHP

on:
  push:
  pull_request:
    types: [synchronize]

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.4', '8.0', '8.1', '8.2', '8.3', '8.4', '8.5']
      fail-fast: false
    name: CI PHP ${{ matrix.php-versions }}

    steps:
      - uses: actions/checkout@v7

      - uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-versions }}

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v4
        with:
          php_version: ${{ matrix.php-versions }}
